/**
 *
 * @author Gullian Van Der Walt H5G8YT7X3
 * ITDA301 - Project 2020
 * Pearson Pretoria 
 * BSC IT Level 3
 * 
 * 
 * 
 * 
 * This Is The Main BroadReach View
 */

package broadreach;

import javax.swing.ImageIcon;

public class Dashboard extends javax.swing.JFrame {
    ImageIcon clinicImg = new ImageIcon("src/images/clinic_Logo.png");
    Login lgn = new Login();
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        header = new java.awt.Label();
        subheading = new java.awt.Label();
        subPanel = new javax.swing.JPanel();
        welcomeLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        selectPanel = new javax.swing.JPanel();
        clinicianBtn = new javax.swing.JButton();
        CHWBtn = new javax.swing.JButton();
        ReceptionistBtn = new javax.swing.JButton();
        adminHBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BroadReach");
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1440, 1080));
        setName("mainFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1920, 1220));
        setSize(new java.awt.Dimension(1440, 1080));
        java.awt.FlowLayout flowLayout3 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 0);
        flowLayout3.setAlignOnBaseline(true);
        getContentPane().setLayout(flowLayout3);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setMinimumSize(new java.awt.Dimension(1500, 1080));
        mainPanel.setPreferredSize(new java.awt.Dimension(1440, 1220));
        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout();
        flowLayout2.setAlignOnBaseline(true);
        mainPanel.setLayout(flowLayout2);

        headPanel.setBackground(new java.awt.Color(0, 46, 93));
        headPanel.setMinimumSize(new java.awt.Dimension(1440, 200));
        headPanel.setPreferredSize(new java.awt.Dimension(1500, 200));
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 20);
        flowLayout1.setAlignOnBaseline(true);
        headPanel.setLayout(flowLayout1);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clinic_Logo.png"))); // NOI18N
        headPanel.add(jLabel1);

        header.setFont(new java.awt.Font("Constantia", 1, 36)); // NOI18N
        header.setForeground(new java.awt.Color(255, 255, 255));
        header.setName(""); // NOI18N
        header.setText("BroadReach");
        headPanel.add(header);

        subheading.setFont(new java.awt.Font("Constantia", 2, 34)); // NOI18N
        subheading.setForeground(new java.awt.Color(255, 255, 255));
        subheading.setText("Empowering Action. Chaging Lives.");
        headPanel.add(subheading);

        mainPanel.add(headPanel);

        subPanel.setBackground(new java.awt.Color(255, 255, 255));
        subPanel.setMinimumSize(new java.awt.Dimension(0, 0));
        subPanel.setPreferredSize(new java.awt.Dimension(1440, 129));

        welcomeLbl.setFont(new java.awt.Font("Cambria", 0, 28)); // NOI18N
        welcomeLbl.setForeground(new java.awt.Color(0, 46, 93));
        welcomeLbl.setText("Welcome");

        jLabel3.setFont(new java.awt.Font("Cambria", 0, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 46, 93));
        jLabel3.setText("Please Login:");

        javax.swing.GroupLayout subPanelLayout = new javax.swing.GroupLayout(subPanel);
        subPanel.setLayout(subPanelLayout);
        subPanelLayout.setHorizontalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelLayout.createSequentialGroup()
                .addGroup(subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(subPanelLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(welcomeLbl))
                    .addGroup(subPanelLayout.createSequentialGroup()
                        .addGap(647, 647, 647)
                        .addComponent(jLabel3)))
                .addContainerGap(634, Short.MAX_VALUE))
        );
        subPanelLayout.setVerticalGroup(
            subPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLbl)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        mainPanel.add(subPanel);

        selectPanel.setBackground(new java.awt.Color(255, 255, 255));
        selectPanel.setMinimumSize(new java.awt.Dimension(500, 592));
        selectPanel.setOpaque(false);
        selectPanel.setPreferredSize(new java.awt.Dimension(1000, 592));
        selectPanel.setLayout(new java.awt.GridLayout(2, 3, 200, 60));

        clinicianBtn.setBackground(new java.awt.Color(0, 46, 93));
        clinicianBtn.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        clinicianBtn.setForeground(new java.awt.Color(255, 255, 255));
        clinicianBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clinician_Logo.png"))); // NOI18N
        clinicianBtn.setText("Clinician");
        clinicianBtn.setToolTipText("Login As Clinician");
        clinicianBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clinicianBtn.setBorderPainted(false);
        clinicianBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clinicianBtn.setDefaultCapable(false);
        clinicianBtn.setMaximumSize(new java.awt.Dimension(308, 256));
        clinicianBtn.setMinimumSize(new java.awt.Dimension(308, 256));
        clinicianBtn.setPreferredSize(new java.awt.Dimension(308, 256));
        clinicianBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clinicianBtnActionPerformed(evt);
            }
        });
        selectPanel.add(clinicianBtn);

        CHWBtn.setBackground(new java.awt.Color(0, 46, 93));
        CHWBtn.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        CHWBtn.setForeground(new java.awt.Color(255, 255, 255));
        CHWBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chw_Logo.png"))); // NOI18N
        CHWBtn.setText("CHW");
        CHWBtn.setToolTipText("Login As CHW");
        CHWBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        CHWBtn.setBorderPainted(false);
        CHWBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CHWBtn.setMaximumSize(new java.awt.Dimension(308, 256));
        CHWBtn.setMinimumSize(new java.awt.Dimension(308, 256));
        CHWBtn.setPreferredSize(new java.awt.Dimension(308, 256));
        CHWBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHWBtnActionPerformed(evt);
            }
        });
        selectPanel.add(CHWBtn);

        ReceptionistBtn.setBackground(new java.awt.Color(0, 46, 93));
        ReceptionistBtn.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        ReceptionistBtn.setForeground(new java.awt.Color(255, 255, 255));
        ReceptionistBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/receptionist_Logo.png"))); // NOI18N
        ReceptionistBtn.setText("Receptionist");
        ReceptionistBtn.setToolTipText("Login As Receptionist");
        ReceptionistBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ReceptionistBtn.setBorderPainted(false);
        ReceptionistBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReceptionistBtn.setIconTextGap(5);
        ReceptionistBtn.setMaximumSize(new java.awt.Dimension(308, 256));
        ReceptionistBtn.setMinimumSize(new java.awt.Dimension(308, 256));
        ReceptionistBtn.setPreferredSize(new java.awt.Dimension(308, 256));
        ReceptionistBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceptionistBtnActionPerformed(evt);
            }
        });
        selectPanel.add(ReceptionistBtn);

        adminHBtn.setBackground(new java.awt.Color(0, 46, 93));
        adminHBtn.setFont(new java.awt.Font("Elephant", 0, 24)); // NOI18N
        adminHBtn.setForeground(new java.awt.Color(255, 255, 255));
        adminHBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/admin_Logo.png"))); // NOI18N
        adminHBtn.setText("Admin");
        adminHBtn.setToolTipText("Login As Administrator");
        adminHBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        adminHBtn.setBorderPainted(false);
        adminHBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminHBtn.setMaximumSize(new java.awt.Dimension(308, 256));
        adminHBtn.setMinimumSize(new java.awt.Dimension(308, 256));
        adminHBtn.setPreferredSize(new java.awt.Dimension(308, 256));
        adminHBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminHBtnActionPerformed(evt);
            }
        });
        selectPanel.add(adminHBtn);

        mainPanel.add(selectPanel);

        getContentPane().add(mainPanel);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    //CHW Button
    private void CHWBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHWBtnActionPerformed
        lgn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CHWBtnActionPerformed
    //Clinician Button
    private void clinicianBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clinicianBtnActionPerformed
        lgn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_clinicianBtnActionPerformed
    //Receptionist Button
    private void ReceptionistBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceptionistBtnActionPerformed
        lgn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ReceptionistBtnActionPerformed
    //Admin Button
    private void adminHBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminHBtnActionPerformed
        lgn.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_adminHBtnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CHWBtn;
    private javax.swing.JButton ReceptionistBtn;
    private javax.swing.JButton adminHBtn;
    private javax.swing.JButton clinicianBtn;
    private javax.swing.JPanel headPanel;
    private java.awt.Label header;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel selectPanel;
    private javax.swing.JPanel subPanel;
    private java.awt.Label subheading;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables

}
