/**
 *
 * @author Gullian Van Der Walt H5G8YT7X3
 * ITDA301 - Project 2020
 * Pearson Pretoria 
 * BSC IT Level 3
 * 
 * 
 * 
 * This Is The Login View
 */
package broadreach;

import broadreach.Admin.AdminHome;
import broadreach.CHW.CHWHome;
import broadreach.Clinician.ClinicianHome;
import broadreach.Receptionist.ReceptionistHome;
import java.util.Scanner;
import javax.swing.JOptionPane;


public class Login extends javax.swing.JFrame {
    
    Scanner input = new Scanner(System.in);
    public String username = "";
    public String password = "";
    
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loingHeadPanel = new javax.swing.JPanel();
        loginLbl = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        loginHeader1 = new java.awt.Label();
        usernameLbl = new javax.swing.JLabel();
        passwordLbl = new javax.swing.JLabel();
        loginHmBtn = new javax.swing.JButton();
        loginLBtn = new javax.swing.JButton();
        usernameTxtFld = new javax.swing.JTextField();
        passwordTxtFld = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BroadReach - Login");
        setBackground(new java.awt.Color(255, 255, 255));
        setName("loginFrame"); // NOI18N
        setResizable(false);

        loingHeadPanel.setBackground(new java.awt.Color(0, 46, 93));
        loingHeadPanel.setMaximumSize(new java.awt.Dimension(500, 100));

        loginLbl.setFont(new java.awt.Font("Constantia", 0, 36)); // NOI18N
        loginLbl.setForeground(new java.awt.Color(255, 255, 255));
        loginLbl.setName(""); // NOI18N
        loginLbl.setText("Login");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user.png"))); // NOI18N

        loginHeader1.setFont(new java.awt.Font("Constantia", 0, 36)); // NOI18N
        loginHeader1.setForeground(new java.awt.Color(255, 255, 255));
        loginHeader1.setName(""); // NOI18N
        loginHeader1.setText("BroadReach");

        javax.swing.GroupLayout loingHeadPanelLayout = new javax.swing.GroupLayout(loingHeadPanel);
        loingHeadPanel.setLayout(loingHeadPanelLayout);
        loingHeadPanelLayout.setHorizontalGroup(
            loingHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loingHeadPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(loginHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(loginLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89))
        );
        loingHeadPanelLayout.setVerticalGroup(
            loingHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loingHeadPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loingHeadPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(loingHeadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loingHeadPanelLayout.createSequentialGroup()
                        .addComponent(loginHeader1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loingHeadPanelLayout.createSequentialGroup()
                        .addComponent(loginLbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );

        usernameLbl.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        usernameLbl.setForeground(new java.awt.Color(0, 46, 93));
        usernameLbl.setText("Username:");

        passwordLbl.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        passwordLbl.setForeground(new java.awt.Color(0, 46, 93));
        passwordLbl.setText("Password");

        loginHmBtn.setBackground(new java.awt.Color(0, 46, 93));
        loginHmBtn.setFont(new java.awt.Font("Elephant", 0, 22)); // NOI18N
        loginHmBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginHmBtn.setText("Home");
        loginHmBtn.setToolTipText("Go Back to BroadReach Dashboard");
        loginHmBtn.setBorderPainted(false);
        loginHmBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginHmBtn.setPreferredSize(new java.awt.Dimension(120, 40));
        loginHmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginHmBtnActionPerformed(evt);
            }
        });

        loginLBtn.setBackground(new java.awt.Color(0, 46, 93));
        loginLBtn.setFont(new java.awt.Font("Elephant", 0, 22)); // NOI18N
        loginLBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginLBtn.setText("Login");
        loginLBtn.setToolTipText("Login To BroadReach ");
        loginLBtn.setBorderPainted(false);
        loginLBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginLBtn.setPreferredSize(new java.awt.Dimension(120, 40));
        loginLBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginLBtnActionPerformed(evt);
            }
        });

        usernameTxtFld.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        usernameTxtFld.setForeground(new java.awt.Color(51, 51, 51));
        usernameTxtFld.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        usernameTxtFld.setToolTipText("Enter Your Username");
        usernameTxtFld.setMinimumSize(new java.awt.Dimension(10, 23));
        usernameTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTxtFldActionPerformed(evt);
            }
        });

        passwordTxtFld.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        passwordTxtFld.setForeground(new java.awt.Color(51, 51, 51));
        passwordTxtFld.setToolTipText("Enter Your Password");
        passwordTxtFld.setMinimumSize(new java.awt.Dimension(10, 23));
        passwordTxtFld.setPreferredSize(new java.awt.Dimension(61, 23));
        passwordTxtFld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtFldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(loingHeadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(passwordLbl)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(loginHmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loginLBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(usernameLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(passwordTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                                    .addComponent(usernameTxtFld, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(133, 133, 133))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(loingHeadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernameLbl)
                    .addComponent(usernameTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLbl)
                    .addComponent(passwordTxtFld, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginHmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loginLBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTxtFldActionPerformed
        username = usernameTxtFld.getText();
    }//GEN-LAST:event_usernameTxtFldActionPerformed

    private void passwordTxtFldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtFldActionPerformed
       password = passwordTxtFld.getText();
    }//GEN-LAST:event_passwordTxtFldActionPerformed

    private void loginHmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginHmBtnActionPerformed
        new Dashboard().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_loginHmBtnActionPerformed

    private void loginLBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginLBtnActionPerformed
        
        username = usernameTxtFld.getText();
        password = passwordTxtFld.getText();
        String passwordDb = "password1";
        //Username and password validation
        switch(username){
            case "Clinician":
                    new ClinicianHome().setVisible(true);
                    this.setVisible(false);
                if ( password.equals(passwordDb)) {
                    new ClinicianHome().setVisible(true);
                    this.setVisible(false);
                }else if (password != "password1"){
                    System.out.println("Invalid Password");
                    JOptionPane.showMessageDialog(null, "Password is incorrect");
                    System.out.println(password);
                }
            break;
            case "clinician":
                if (password.equals(passwordDb)) {
                    new ClinicianHome().setVisible(true);
                    this.setVisible(false);
                }else if (password != "password1"){
                    System.out.println("Invalid Password");
                    JOptionPane.showMessageDialog(null, "Password is incorrect");
                    System.out.println(password);
                }
                
            break;
            
            case "CHW":
                if (password.equals(passwordDb)) {
                        new CHWHome().setVisible(true);
                        this.setVisible(false);
                }else{
                        System.out.println("Invalid Password");
                        JOptionPane.showMessageDialog(null, "Password is incorrect");
                }
            break;    
            case "chw":
                if (password.equals(passwordDb)) {
                        new CHWHome().setVisible(true);
                        this.setVisible(false);
                }else{
                        System.out.println("Invalid Password");
                        JOptionPane.showMessageDialog(null, "Password is incorrect");
                }                
                
            break;    
            case "Receptionist":
                if (password.equals(passwordDb)) {
                        new ReceptionistHome().setVisible(true);
                        this.setVisible(false);
                }else{
                        System.out.println("Invalid Password");
                        JOptionPane.showMessageDialog(null, "Password is incorrect");
                }
            break;
            case "receptionist":
                if (password.equals(passwordDb)) {
                    new ReceptionistHome().setVisible(true);
                    this.setVisible(false);
                }else{
                    System.out.println("Invalid Password");
                    JOptionPane.showMessageDialog(null, "Password is incorrect");
                }
            break;
            case "Admin":
                if (password.equals(passwordDb)) {
                        new AdminHome().setVisible(true);
                        this.setVisible(false);
                }else{
                        System.out.println("Invalid Password");
                        JOptionPane.showMessageDialog(null, "Password is incorrect");
                }
            break;         
            case "admin":
                if (password.equals(passwordDb)) {
                    new AdminHome().setVisible(true);
                    this.setVisible(false);
                }else if (password != "password1"){
                    System.out.println("Invalid Password");
                    JOptionPane.showMessageDialog(null, "Password is incorrect");
                    System.out.println(password);
                }   
            break;
            default:
                JOptionPane.showMessageDialog(null, "Invalid Username");
                System.out.println(usernameTxtFld.getText());
        }
    }//GEN-LAST:event_loginLBtnActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private java.awt.Label loginHeader1;
    private javax.swing.JButton loginHmBtn;
    private javax.swing.JButton loginLBtn;
    private java.awt.Label loginLbl;
    private javax.swing.JPanel loingHeadPanel;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JTextField passwordTxtFld;
    private javax.swing.JLabel usernameLbl;
    private javax.swing.JTextField usernameTxtFld;
    // End of variables declaration//GEN-END:variables
}
