/**
 *
 * @author Gullian Van Der Walt H5G8YT7X3
 * ITDA301 - Project 2020
 * Pearson Pretoria 
 * BSC IT Level 3
 * 
 * 
 * 
 * This Is The Main Clinician View
 * 
 * 
 */
package broadreach.Clinician;

import broadreach.Dashboard;


public class ClinicianHome extends javax.swing.JFrame {

    /**
     * Creates new form ClinicianHome
     */
    public ClinicianHome() {
        initComponents();
        setExtendedState(getExtendedState() | ClinicianHome.MAXIMIZED_BOTH );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headPanel = new javax.swing.JPanel();
        headSubPanel1 = new javax.swing.JPanel();
        logoutBtn = new javax.swing.JButton();
        headSubPanel2 = new javax.swing.JPanel();
        clinicianIconLbl = new javax.swing.JLabel();
        clinicHeadLbl = new javax.swing.JLabel();
        subheadingLbl = new javax.swing.JLabel();
        headSubPanel3 = new javax.swing.JPanel();
        exitBtn = new javax.swing.JButton();
        bodyPanel = new javax.swing.JPanel();
        subBodyPanel = new javax.swing.JPanel();
        examBtn = new javax.swing.JButton();
        prescripBtn = new javax.swing.JButton();
        diagnosisBtn = new javax.swing.JButton();
        appBtn = new javax.swing.JButton();
        patientsBtn2 = new javax.swing.JButton();
        testsBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BroadReach - Clinician Home");
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1450, 1080));
        setName("clinicianHomeFrame"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1450, 1080));
        setSize(new java.awt.Dimension(1920, 1080));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setMaximumSize(new java.awt.Dimension(1920, 1080));
        mainPanel.setMinimumSize(new java.awt.Dimension(1920, 1080));
        mainPanel.setPreferredSize(new java.awt.Dimension(1920, 1080));

        headPanel.setBackground(new java.awt.Color(0, 46, 93));
        headPanel.setMaximumSize(new java.awt.Dimension(1920, 227));
        headPanel.setMinimumSize(new java.awt.Dimension(1440, 227));
        headPanel.setPreferredSize(new java.awt.Dimension(1920, 225));
        headPanel.setLayout(new java.awt.GridLayout(1, 1));

        headSubPanel1.setBackground(new java.awt.Color(0, 46, 93));
        headSubPanel1.setPreferredSize(new java.awt.Dimension(640, 227));

        logoutBtn.setBackground(new java.awt.Color(0, 46, 93));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout_icon.png"))); // NOI18N
        logoutBtn.setToolTipText("Exit BroadReach");
        logoutBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logoutBtn.setBorderPainted(false);
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.setDefaultCapable(false);
        logoutBtn.setPreferredSize(new java.awt.Dimension(97, 97));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headSubPanel1Layout = new javax.swing.GroupLayout(headSubPanel1);
        headSubPanel1.setLayout(headSubPanel1Layout);
        headSubPanel1Layout.setHorizontalGroup(
            headSubPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headSubPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(533, Short.MAX_VALUE))
        );
        headSubPanel1Layout.setVerticalGroup(
            headSubPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headSubPanel1Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        headPanel.add(headSubPanel1);

        headSubPanel2.setBackground(new java.awt.Color(0, 46, 93));
        headSubPanel2.setPreferredSize(new java.awt.Dimension(640, 227));

        clinicianIconLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clinician_Logo.png"))); // NOI18N

        clinicHeadLbl.setFont(new java.awt.Font("Constantia", 1, 36)); // NOI18N
        clinicHeadLbl.setForeground(new java.awt.Color(255, 255, 255));
        clinicHeadLbl.setText("Clinician");
        clinicHeadLbl.setToolTipText("");
        clinicHeadLbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        subheadingLbl.setFont(new java.awt.Font("Constantia", 1, 36)); // NOI18N
        subheadingLbl.setForeground(new java.awt.Color(255, 255, 255));
        subheadingLbl.setText("BroadReach Clinic");
        subheadingLbl.setToolTipText("");
        subheadingLbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout headSubPanel2Layout = new javax.swing.GroupLayout(headSubPanel2);
        headSubPanel2.setLayout(headSubPanel2Layout);
        headSubPanel2Layout.setHorizontalGroup(
            headSubPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headSubPanel2Layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addGroup(headSubPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headSubPanel2Layout.createSequentialGroup()
                        .addComponent(clinicianIconLbl)
                        .addGap(18, 18, 18)
                        .addComponent(clinicHeadLbl)
                        .addGap(217, 217, 217))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headSubPanel2Layout.createSequentialGroup()
                        .addComponent(subheadingLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138))))
        );
        headSubPanel2Layout.setVerticalGroup(
            headSubPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headSubPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(subheadingLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(headSubPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clinicianIconLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headSubPanel2Layout.createSequentialGroup()
                        .addComponent(clinicHeadLbl)
                        .addGap(21, 21, 21))))
        );

        headPanel.add(headSubPanel2);

        headSubPanel3.setBackground(new java.awt.Color(0, 46, 93));
        headSubPanel3.setPreferredSize(new java.awt.Dimension(640, 227));

        exitBtn.setBackground(new java.awt.Color(0, 46, 93));
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit_icon.png"))); // NOI18N
        exitBtn.setToolTipText("Exit BroadReach");
        exitBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitBtn.setBorderPainted(false);
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.setDefaultCapable(false);
        exitBtn.setPreferredSize(new java.awt.Dimension(97, 97));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headSubPanel3Layout = new javax.swing.GroupLayout(headSubPanel3);
        headSubPanel3.setLayout(headSubPanel3Layout);
        headSubPanel3Layout.setHorizontalGroup(
            headSubPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headSubPanel3Layout.createSequentialGroup()
                .addContainerGap(533, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headSubPanel3Layout.setVerticalGroup(
            headSubPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headSubPanel3Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        headPanel.add(headSubPanel3);

        mainPanel.add(headPanel);

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setForeground(new java.awt.Color(0, 46, 93));
        bodyPanel.setMinimumSize(new java.awt.Dimension(1920, 853));
        bodyPanel.setPreferredSize(new java.awt.Dimension(1920, 853));
        bodyPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 100));

        subBodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        subBodyPanel.setMinimumSize(new java.awt.Dimension(900, 853));
        subBodyPanel.setPreferredSize(new java.awt.Dimension(1200, 600));
        subBodyPanel.setLayout(new java.awt.GridLayout(2, 3, 60, 60));

        examBtn.setBackground(new java.awt.Color(0, 46, 93));
        examBtn.setFont(new java.awt.Font("Elephant", 0, 26)); // NOI18N
        examBtn.setForeground(new java.awt.Color(255, 255, 255));
        examBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exam_Logo.png"))); // NOI18N
        examBtn.setText("Examination");
        examBtn.setBorderPainted(false);
        examBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        examBtn.setPreferredSize(new java.awt.Dimension(308, 256));
        examBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examBtnActionPerformed(evt);
            }
        });
        subBodyPanel.add(examBtn);

        prescripBtn.setBackground(new java.awt.Color(0, 46, 93));
        prescripBtn.setFont(new java.awt.Font("Elephant", 0, 26)); // NOI18N
        prescripBtn.setForeground(new java.awt.Color(255, 255, 255));
        prescripBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/prescription_logo.png"))); // NOI18N
        prescripBtn.setText("Prescription");
        prescripBtn.setToolTipText("Make new prescription or view old one");
        prescripBtn.setBorderPainted(false);
        prescripBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        prescripBtn.setPreferredSize(new java.awt.Dimension(308, 256));
        prescripBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prescripBtnActionPerformed(evt);
            }
        });
        subBodyPanel.add(prescripBtn);

        diagnosisBtn.setBackground(new java.awt.Color(0, 46, 93));
        diagnosisBtn.setFont(new java.awt.Font("Elephant", 0, 26)); // NOI18N
        diagnosisBtn.setForeground(new java.awt.Color(255, 255, 255));
        diagnosisBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/diagnosis.png"))); // NOI18N
        diagnosisBtn.setText("Diagnosis");
        diagnosisBtn.setToolTipText("New diagnosis or view old one");
        diagnosisBtn.setBorderPainted(false);
        diagnosisBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        diagnosisBtn.setPreferredSize(new java.awt.Dimension(308, 256));
        diagnosisBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnosisBtnActionPerformed(evt);
            }
        });
        subBodyPanel.add(diagnosisBtn);

        appBtn.setBackground(new java.awt.Color(0, 46, 93));
        appBtn.setFont(new java.awt.Font("Elephant", 0, 26)); // NOI18N
        appBtn.setForeground(new java.awt.Color(255, 255, 255));
        appBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/appointment_icon.png"))); // NOI18N
        appBtn.setText("Appointment");
        appBtn.setToolTipText("Make new appointment or view old");
        appBtn.setBorderPainted(false);
        appBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        appBtn.setPreferredSize(new java.awt.Dimension(308, 256));
        appBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                appBtnActionPerformed(evt);
            }
        });
        subBodyPanel.add(appBtn);

        patientsBtn2.setBackground(new java.awt.Color(0, 46, 93));
        patientsBtn2.setFont(new java.awt.Font("Elephant", 0, 26)); // NOI18N
        patientsBtn2.setForeground(new java.awt.Color(255, 255, 255));
        patientsBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/patient_icon.png"))); // NOI18N
        patientsBtn2.setText("Patients");
        patientsBtn2.setBorderPainted(false);
        patientsBtn2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        patientsBtn2.setPreferredSize(new java.awt.Dimension(308, 256));
        patientsBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patientsBtn2ActionPerformed(evt);
            }
        });
        subBodyPanel.add(patientsBtn2);

        testsBtn.setBackground(new java.awt.Color(0, 46, 93));
        testsBtn.setFont(new java.awt.Font("Elephant", 0, 26)); // NOI18N
        testsBtn.setForeground(new java.awt.Color(255, 255, 255));
        testsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lab_Logo.png"))); // NOI18N
        testsBtn.setText("Tests");
        testsBtn.setToolTipText("Test request, or view tests");
        testsBtn.setBorderPainted(false);
        testsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        testsBtn.setPreferredSize(new java.awt.Dimension(308, 256));
        testsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testsBtnActionPerformed(evt);
            }
        });
        subBodyPanel.add(testsBtn);

        bodyPanel.add(subBodyPanel);

        mainPanel.add(bodyPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Examination Button
    private void examBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examBtnActionPerformed
        new ExaminationNav().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_examBtnActionPerformed
    //Prescription Button
    private void prescripBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prescripBtnActionPerformed
        new PrescriptionNav().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_prescripBtnActionPerformed
    //Tests Button
    private void testsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testsBtnActionPerformed
        new TestNav().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_testsBtnActionPerformed
    //Diagnosis Button
    private void diagnosisBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosisBtnActionPerformed
        new DiagnosisNav().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_diagnosisBtnActionPerformed
    //Appointments Button
    private void appBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_appBtnActionPerformed
        new AppointmentNav().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_appBtnActionPerformed
    //Patients Button
    private void patientsBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patientsBtn2ActionPerformed
        new PatientsNav().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_patientsBtn2ActionPerformed

    //Exit Button
    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
       new Dashboard().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_logoutBtnActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClinicianHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClinicianHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClinicianHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClinicianHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClinicianHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton appBtn;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JLabel clinicHeadLbl;
    private javax.swing.JLabel clinicianIconLbl;
    private javax.swing.JButton diagnosisBtn;
    private javax.swing.JButton examBtn;
    private javax.swing.JButton exitBtn;
    private javax.swing.JPanel headPanel;
    private javax.swing.JPanel headSubPanel1;
    private javax.swing.JPanel headSubPanel2;
    private javax.swing.JPanel headSubPanel3;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton patientsBtn2;
    private javax.swing.JButton prescripBtn;
    private javax.swing.JPanel subBodyPanel;
    private javax.swing.JLabel subheadingLbl;
    private javax.swing.JButton testsBtn;
    // End of variables declaration//GEN-END:variables
}
