/**
 *
 * @author Gullian Van Der Walt 
 * H5G8YT7X3
 * ITDA301 - Project 2020
 * Pearson Pretoria 
 * BSC IT Level 3
 * 
 * 
 * 
 * This Is The New Examination View
 * 
 * 
 */
package broadreach.Clinician;

public class NewExamination2 extends javax.swing.JFrame {

    /**
     * Creates new form NewExamination2
     */
    public NewExamination2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newExamPanel2 = new javax.swing.JPanel();
        headPanel1 = new javax.swing.JPanel();
        headSubPanel2 = new javax.swing.JPanel();
        backBtn1 = new javax.swing.JButton();
        headSubPanel3 = new javax.swing.JPanel();
        examIcon = new javax.swing.JLabel();
        newExamLbl = new javax.swing.JLabel();
        subheadingLbl = new javax.swing.JLabel();
        headSubPanel4 = new javax.swing.JPanel();
        exitBtn = new javax.swing.JButton();
        bodyPanel = new javax.swing.JPanel();
        subBodyPanel = new javax.swing.JPanel();
        notesLbl = new javax.swing.JLabel();
        timeTxtFld = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ExamRTxtArea = new javax.swing.JTextArea();
        clinicianIDLbl = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        patientIDLbl = new javax.swing.JLabel();
        timeLbl = new javax.swing.JLabel();
        patientIDTxtFld = new javax.swing.JTextField();
        dateTxtFld1 = new javax.swing.JTextField();
        dateLbl1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        findingsTxtArea = new javax.swing.JTextArea();
        notesLbl1 = new javax.swing.JLabel();
        btnPanel = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BroadReach - New Examination");

        newExamPanel2.setBackground(new java.awt.Color(255, 255, 255));
        newExamPanel2.setMaximumSize(new java.awt.Dimension(1920, 1080));
        newExamPanel2.setMinimumSize(new java.awt.Dimension(1920, 1080));
        newExamPanel2.setPreferredSize(new java.awt.Dimension(1920, 1080));

        headPanel1.setBackground(new java.awt.Color(0, 46, 93));
        headPanel1.setMaximumSize(new java.awt.Dimension(1920, 227));
        headPanel1.setMinimumSize(new java.awt.Dimension(1440, 227));
        headPanel1.setPreferredSize(new java.awt.Dimension(1920, 225));
        headPanel1.setLayout(new java.awt.GridLayout(1, 1));

        headSubPanel2.setBackground(new java.awt.Color(0, 46, 93));
        headSubPanel2.setPreferredSize(new java.awt.Dimension(640, 227));

        backBtn1.setBackground(new java.awt.Color(0, 46, 93));
        backBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_icon.png"))); // NOI18N
        backBtn1.setToolTipText("Exit BroadReach");
        backBtn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backBtn1.setBorderPainted(false);
        backBtn1.setContentAreaFilled(false);
        backBtn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn1.setDefaultCapable(false);
        backBtn1.setPreferredSize(new java.awt.Dimension(97, 97));
        backBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headSubPanel2Layout = new javax.swing.GroupLayout(headSubPanel2);
        headSubPanel2.setLayout(headSubPanel2Layout);
        headSubPanel2Layout.setHorizontalGroup(
            headSubPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headSubPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(533, Short.MAX_VALUE))
        );
        headSubPanel2Layout.setVerticalGroup(
            headSubPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headSubPanel2Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(backBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        headPanel1.add(headSubPanel2);

        headSubPanel3.setBackground(new java.awt.Color(0, 46, 93));
        headSubPanel3.setPreferredSize(new java.awt.Dimension(640, 227));

        examIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exam_Logo.png"))); // NOI18N

        newExamLbl.setFont(new java.awt.Font("Constantia", 1, 36)); // NOI18N
        newExamLbl.setForeground(new java.awt.Color(255, 255, 255));
        newExamLbl.setText("New Examination");
        newExamLbl.setToolTipText("");
        newExamLbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        subheadingLbl.setFont(new java.awt.Font("Constantia", 1, 36)); // NOI18N
        subheadingLbl.setForeground(new java.awt.Color(255, 255, 255));
        subheadingLbl.setText("BroadReach Clinic");
        subheadingLbl.setToolTipText("");
        subheadingLbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout headSubPanel3Layout = new javax.swing.GroupLayout(headSubPanel3);
        headSubPanel3.setLayout(headSubPanel3Layout);
        headSubPanel3Layout.setHorizontalGroup(
            headSubPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headSubPanel3Layout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(headSubPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headSubPanel3Layout.createSequentialGroup()
                        .addComponent(examIcon)
                        .addGap(26, 26, 26)
                        .addComponent(newExamLbl)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headSubPanel3Layout.createSequentialGroup()
                        .addComponent(subheadingLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138))))
        );
        headSubPanel3Layout.setVerticalGroup(
            headSubPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headSubPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(subheadingLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(headSubPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newExamLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(examIcon, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(22, 22, 22))
        );

        headPanel1.add(headSubPanel3);

        headSubPanel4.setBackground(new java.awt.Color(0, 46, 93));
        headSubPanel4.setPreferredSize(new java.awt.Dimension(640, 227));

        exitBtn.setBackground(new java.awt.Color(0, 46, 93));
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit_icon.png"))); // NOI18N
        exitBtn.setToolTipText("Exit BroadReach");
        exitBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitBtn.setBorderPainted(false);
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.setDefaultCapable(false);
        exitBtn.setPreferredSize(new java.awt.Dimension(97, 97));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headSubPanel4Layout = new javax.swing.GroupLayout(headSubPanel4);
        headSubPanel4.setLayout(headSubPanel4Layout);
        headSubPanel4Layout.setHorizontalGroup(
            headSubPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headSubPanel4Layout.createSequentialGroup()
                .addContainerGap(533, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headSubPanel4Layout.setVerticalGroup(
            headSubPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headSubPanel4Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        headPanel1.add(headSubPanel4);

        newExamPanel2.add(headPanel1);

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setForeground(new java.awt.Color(0, 46, 93));
        bodyPanel.setMinimumSize(new java.awt.Dimension(1920, 853));
        bodyPanel.setPreferredSize(new java.awt.Dimension(1920, 853));
        bodyPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 50));

        subBodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        subBodyPanel.setMinimumSize(new java.awt.Dimension(900, 853));
        subBodyPanel.setPreferredSize(new java.awt.Dimension(1100, 500));
        subBodyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        notesLbl.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        notesLbl.setForeground(new java.awt.Color(0, 46, 93));
        notesLbl.setText("Examination Reason:");
        notesLbl.setToolTipText("Enter Clinician ID");
        subBodyPanel.add(notesLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, -1, -1));

        timeTxtFld.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        timeTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 46, 93), 2));
        timeTxtFld.setPreferredSize(new java.awt.Dimension(240, 30));
        subBodyPanel.add(timeTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, -1));

        ExamRTxtArea.setColumns(20);
        ExamRTxtArea.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ExamRTxtArea.setRows(5);
        ExamRTxtArea.setPreferredSize(new java.awt.Dimension(250, 200));
        jScrollPane2.setViewportView(ExamRTxtArea);

        subBodyPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 280, 280));

        clinicianIDLbl.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        clinicianIDLbl.setForeground(new java.awt.Color(0, 46, 93));
        clinicianIDLbl.setText("Clinician ID:");
        clinicianIDLbl.setToolTipText("Enter Clinician ID");
        subBodyPanel.add(clinicianIDLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jTextField5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 46, 93), 2));
        jTextField5.setPreferredSize(new java.awt.Dimension(240, 30));
        subBodyPanel.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        patientIDLbl.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        patientIDLbl.setForeground(new java.awt.Color(0, 46, 93));
        patientIDLbl.setText("Patient ID:");
        patientIDLbl.setToolTipText("Enter Clinician ID");
        subBodyPanel.add(patientIDLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        timeLbl.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        timeLbl.setForeground(new java.awt.Color(0, 46, 93));
        timeLbl.setText("Time:");
        timeLbl.setToolTipText("Enter Clinician ID");
        subBodyPanel.add(timeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, -1));

        patientIDTxtFld.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        patientIDTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 46, 93), 2));
        patientIDTxtFld.setPreferredSize(new java.awt.Dimension(240, 30));
        subBodyPanel.add(patientIDTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        dateTxtFld1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dateTxtFld1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 46, 93), 2));
        dateTxtFld1.setPreferredSize(new java.awt.Dimension(240, 30));
        subBodyPanel.add(dateTxtFld1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        dateLbl1.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        dateLbl1.setForeground(new java.awt.Color(0, 46, 93));
        dateLbl1.setText("Date:");
        dateLbl1.setToolTipText("Enter Clinician ID");
        subBodyPanel.add(dateLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, -1, -1));

        findingsTxtArea.setColumns(20);
        findingsTxtArea.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        findingsTxtArea.setRows(5);
        findingsTxtArea.setPreferredSize(new java.awt.Dimension(250, 200));
        jScrollPane3.setViewportView(findingsTxtArea);

        subBodyPanel.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 270, 280));

        notesLbl1.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        notesLbl1.setForeground(new java.awt.Color(0, 46, 93));
        notesLbl1.setText("Findings:");
        notesLbl1.setToolTipText("Enter Clinician ID");
        subBodyPanel.add(notesLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 90, -1, -1));

        bodyPanel.add(subBodyPanel);

        btnPanel.setBackground(new java.awt.Color(255, 255, 255));
        btnPanel.setPreferredSize(new java.awt.Dimension(1900, 200));
        btnPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 500, 30));

        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new_list.png"))); // NOI18N
        addBtn.setToolTipText("New Examination");
        addBtn.setBorderPainted(false);
        addBtn.setContentAreaFilled(false);
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        btnPanel.add(addBtn);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        homeBtn.setToolTipText("Go To Dashboard");
        homeBtn.setBorderPainted(false);
        homeBtn.setContentAreaFilled(false);
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        btnPanel.add(homeBtn);

        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        saveBtn.setToolTipText("Save Test Examination");
        saveBtn.setBorderPainted(false);
        saveBtn.setContentAreaFilled(false);
        saveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        btnPanel.add(saveBtn);

        bodyPanel.add(btnPanel);

        newExamPanel2.add(bodyPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newExamPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(newExamPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtn1ActionPerformed
        new NewExamination().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBtn1ActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    //New Examination Button
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        new NewExamination().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addBtnActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        new ClinicianHome().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed

    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewExamination2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewExamination2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewExamination2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewExamination2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewExamination2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ExamRTxtArea;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton backBtn1;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JLabel clinicianIDLbl;
    private javax.swing.JLabel dateLbl1;
    private javax.swing.JTextField dateTxtFld1;
    private javax.swing.JLabel examIcon;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextArea findingsTxtArea;
    private javax.swing.JPanel headPanel;
    private javax.swing.JPanel headPanel1;
    private javax.swing.JPanel headSubPanel1;
    private javax.swing.JPanel headSubPanel2;
    private javax.swing.JPanel headSubPanel3;
    private javax.swing.JPanel headSubPanel4;
    private javax.swing.JButton homeBtn;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel newExamLbl;
    private javax.swing.JPanel newExamPanel2;
    private javax.swing.JLabel notesLbl;
    private javax.swing.JLabel notesLbl1;
    private javax.swing.JLabel patientIDLbl;
    private javax.swing.JTextField patientIDTxtFld;
    private javax.swing.JButton saveBtn;
    private javax.swing.JPanel subBodyPanel;
    private javax.swing.JLabel subheadingLbl;
    private javax.swing.JPanel testReqPanel3;
    private javax.swing.JLabel timeLbl;
    private javax.swing.JTextField timeTxtFld;
    // End of variables declaration//GEN-END:variables
}
