/**
 *
 * @author Gullian Van Der Walt 
 * H5G8YT7X3
 * ITDA301 - Project 2020
 * Pearson Pretoria 
 * BSC IT Level 3
 * 
 * 
 * 
 * This Is The New Test Request View
 * 
 * 
 */
package broadreach.Clinician;

public class NewTestRequest3 extends javax.swing.JFrame {

    /**
     * Creates new form TestRequest3
     */
    public NewTestRequest3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        testReqPanel3 = new javax.swing.JPanel();
        headPanel = new javax.swing.JPanel();
        headSubPanel1 = new javax.swing.JPanel();
        backBtn = new javax.swing.JButton();
        headSubPanel2 = new javax.swing.JPanel();
        labIcon = new javax.swing.JLabel();
        testReqLbl3 = new javax.swing.JLabel();
        subheadingLbl = new javax.swing.JLabel();
        headSubPanel3 = new javax.swing.JPanel();
        exitBtn = new javax.swing.JButton();
        bodyPanel = new javax.swing.JPanel();
        subBodyPanel = new javax.swing.JPanel();
        notesLbl = new javax.swing.JLabel();
        patientIDTxtFld = new javax.swing.JTextField();
        labIDCmbBx = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        notesTxtArea = new javax.swing.JTextArea();
        clinicianIDLbl1 = new javax.swing.JLabel();
        clinicianIDTxtFld = new javax.swing.JTextField();
        examTxtFld = new javax.swing.JTextField();
        dateLbl = new javax.swing.JLabel();
        patientIDLbl1 = new javax.swing.JLabel();
        testTypeLbl1 = new javax.swing.JLabel();
        exmaIDLbl = new javax.swing.JLabel();
        dateTxtFld1 = new javax.swing.JTextField();
        testTypeCmbBx1 = new javax.swing.JComboBox();
        labIDlbl1 = new javax.swing.JLabel();
        btnPanel = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BroadReach - Test Request");
        setName("testReqFrame3"); // NOI18N

        testReqPanel3.setBackground(new java.awt.Color(255, 255, 255));
        testReqPanel3.setMaximumSize(new java.awt.Dimension(1920, 1080));
        testReqPanel3.setMinimumSize(new java.awt.Dimension(1920, 1080));
        testReqPanel3.setPreferredSize(new java.awt.Dimension(1920, 1080));

        headPanel.setBackground(new java.awt.Color(0, 46, 93));
        headPanel.setMaximumSize(new java.awt.Dimension(1920, 227));
        headPanel.setMinimumSize(new java.awt.Dimension(1440, 227));
        headPanel.setPreferredSize(new java.awt.Dimension(1920, 225));
        headPanel.setLayout(new java.awt.GridLayout(1, 1));

        headSubPanel1.setBackground(new java.awt.Color(0, 46, 93));
        headSubPanel1.setPreferredSize(new java.awt.Dimension(640, 227));

        backBtn.setBackground(new java.awt.Color(0, 46, 93));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back_icon.png"))); // NOI18N
        backBtn.setToolTipText("Exit BroadReach");
        backBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backBtn.setBorderPainted(false);
        backBtn.setContentAreaFilled(false);
        backBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backBtn.setDefaultCapable(false);
        backBtn.setPreferredSize(new java.awt.Dimension(97, 97));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headSubPanel1Layout = new javax.swing.GroupLayout(headSubPanel1);
        headSubPanel1.setLayout(headSubPanel1Layout);
        headSubPanel1Layout.setHorizontalGroup(
            headSubPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headSubPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(533, Short.MAX_VALUE))
        );
        headSubPanel1Layout.setVerticalGroup(
            headSubPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headSubPanel1Layout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        headPanel.add(headSubPanel1);

        headSubPanel2.setBackground(new java.awt.Color(0, 46, 93));
        headSubPanel2.setPreferredSize(new java.awt.Dimension(640, 227));

        labIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lab_Logo.png"))); // NOI18N

        testReqLbl3.setFont(new java.awt.Font("Constantia", 1, 36)); // NOI18N
        testReqLbl3.setForeground(new java.awt.Color(255, 255, 255));
        testReqLbl3.setText("Test Request");
        testReqLbl3.setToolTipText("");
        testReqLbl3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        subheadingLbl.setFont(new java.awt.Font("Constantia", 1, 36)); // NOI18N
        subheadingLbl.setForeground(new java.awt.Color(255, 255, 255));
        subheadingLbl.setText("BroadReach Clinic");
        subheadingLbl.setToolTipText("");
        subheadingLbl.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout headSubPanel2Layout = new javax.swing.GroupLayout(headSubPanel2);
        headSubPanel2.setLayout(headSubPanel2Layout);
        headSubPanel2Layout.setHorizontalGroup(
            headSubPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headSubPanel2Layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addGroup(headSubPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headSubPanel2Layout.createSequentialGroup()
                        .addComponent(labIcon)
                        .addGap(26, 26, 26)
                        .addComponent(testReqLbl3)
                        .addGap(146, 146, 146))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headSubPanel2Layout.createSequentialGroup()
                        .addComponent(subheadingLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(138, 138, 138))))
        );
        headSubPanel2Layout.setVerticalGroup(
            headSubPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headSubPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(subheadingLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(headSubPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labIcon, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headSubPanel2Layout.createSequentialGroup()
                        .addComponent(testReqLbl3)
                        .addGap(22, 22, 22))))
        );

        headPanel.add(headSubPanel2);

        headSubPanel3.setBackground(new java.awt.Color(0, 46, 93));
        headSubPanel3.setPreferredSize(new java.awt.Dimension(640, 227));

        exitBtn.setBackground(new java.awt.Color(0, 46, 93));
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit_icon.png"))); // NOI18N
        exitBtn.setToolTipText("Exit BroadReach");
        exitBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitBtn.setBorderPainted(false);
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.setDefaultCapable(false);
        exitBtn.setPreferredSize(new java.awt.Dimension(97, 97));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headSubPanel3Layout = new javax.swing.GroupLayout(headSubPanel3);
        headSubPanel3.setLayout(headSubPanel3Layout);
        headSubPanel3Layout.setHorizontalGroup(
            headSubPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headSubPanel3Layout.createSequentialGroup()
                .addContainerGap(533, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headSubPanel3Layout.setVerticalGroup(
            headSubPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headSubPanel3Layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        headPanel.add(headSubPanel3);

        testReqPanel3.add(headPanel);

        bodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        bodyPanel.setForeground(new java.awt.Color(0, 46, 93));
        bodyPanel.setMinimumSize(new java.awt.Dimension(1920, 853));
        bodyPanel.setPreferredSize(new java.awt.Dimension(1920, 853));
        bodyPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 100, 50));

        subBodyPanel.setBackground(new java.awt.Color(255, 255, 255));
        subBodyPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 46, 93), 3, true));
        subBodyPanel.setMinimumSize(new java.awt.Dimension(900, 853));
        subBodyPanel.setPreferredSize(new java.awt.Dimension(1100, 500));
        subBodyPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        notesLbl.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        notesLbl.setForeground(new java.awt.Color(0, 46, 93));
        notesLbl.setText("Notes:");
        notesLbl.setToolTipText("");
        subBodyPanel.add(notesLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 90, -1, -1));

        patientIDTxtFld.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        patientIDTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 46, 93), 2));
        patientIDTxtFld.setPreferredSize(new java.awt.Dimension(240, 30));
        subBodyPanel.add(patientIDTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        labIDCmbBx.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lab001", "Lab001", "radio001" }));
        labIDCmbBx.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 46, 93), 2));
        labIDCmbBx.setPreferredSize(new java.awt.Dimension(240, 30));
        subBodyPanel.add(labIDCmbBx, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        notesTxtArea.setColumns(20);
        notesTxtArea.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        notesTxtArea.setRows(5);
        notesTxtArea.setPreferredSize(new java.awt.Dimension(250, 200));
        jScrollPane2.setViewportView(notesTxtArea);

        subBodyPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, 250, 280));

        clinicianIDLbl1.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        clinicianIDLbl1.setForeground(new java.awt.Color(0, 46, 93));
        clinicianIDLbl1.setText("Clinician ID:");
        clinicianIDLbl1.setToolTipText("");
        subBodyPanel.add(clinicianIDLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        clinicianIDTxtFld.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        clinicianIDTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 46, 93), 2));
        clinicianIDTxtFld.setPreferredSize(new java.awt.Dimension(240, 30));
        subBodyPanel.add(clinicianIDTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        examTxtFld.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        examTxtFld.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 46, 93), 2));
        examTxtFld.setPreferredSize(new java.awt.Dimension(240, 30));
        subBodyPanel.add(examTxtFld, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, -1));

        dateLbl.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        dateLbl.setForeground(new java.awt.Color(0, 46, 93));
        dateLbl.setText("Date:");
        dateLbl.setToolTipText("");
        subBodyPanel.add(dateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, -1, -1));

        patientIDLbl1.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        patientIDLbl1.setForeground(new java.awt.Color(0, 46, 93));
        patientIDLbl1.setText("Patient ID:");
        patientIDLbl1.setToolTipText("");
        subBodyPanel.add(patientIDLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, -1));

        testTypeLbl1.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        testTypeLbl1.setForeground(new java.awt.Color(0, 46, 93));
        testTypeLbl1.setText("Test Type:");
        testTypeLbl1.setToolTipText("");
        subBodyPanel.add(testTypeLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, -1));

        exmaIDLbl.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        exmaIDLbl.setForeground(new java.awt.Color(0, 46, 93));
        exmaIDLbl.setText("Exam ID:");
        exmaIDLbl.setToolTipText("");
        subBodyPanel.add(exmaIDLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, -1, -1));

        dateTxtFld1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dateTxtFld1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 46, 93), 2));
        dateTxtFld1.setPreferredSize(new java.awt.Dimension(240, 30));
        subBodyPanel.add(dateTxtFld1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        testTypeCmbBx1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Diabetes", "HIV", "COVID-19", "Pregnancy" }));
        testTypeCmbBx1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 46, 93), 2));
        testTypeCmbBx1.setPreferredSize(new java.awt.Dimension(240, 30));
        subBodyPanel.add(testTypeCmbBx1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        labIDlbl1.setFont(new java.awt.Font("Constantia", 0, 24)); // NOI18N
        labIDlbl1.setForeground(new java.awt.Color(0, 46, 93));
        labIDlbl1.setText("Lab ID:");
        labIDlbl1.setToolTipText("");
        subBodyPanel.add(labIDlbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, -1, -1));

        bodyPanel.add(subBodyPanel);

        btnPanel.setBackground(new java.awt.Color(255, 255, 255));
        btnPanel.setPreferredSize(new java.awt.Dimension(1900, 200));
        btnPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 500, 30));

        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/new_list.png"))); // NOI18N
        addBtn.setToolTipText("New Test Request");
        addBtn.setBorderPainted(false);
        addBtn.setContentAreaFilled(false);
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        btnPanel.add(addBtn);

        homeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home.png"))); // NOI18N
        homeBtn.setToolTipText("Go To Dashboard");
        homeBtn.setBorderPainted(false);
        homeBtn.setContentAreaFilled(false);
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        btnPanel.add(homeBtn);

        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/save.png"))); // NOI18N
        saveBtn.setToolTipText("Save Test Request");
        saveBtn.setBorderPainted(false);
        saveBtn.setContentAreaFilled(false);
        saveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        btnPanel.add(saveBtn);

        bodyPanel.add(btnPanel);

        testReqPanel3.add(bodyPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(testReqPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(testReqPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Exit Button
    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    //Back Button
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        new NewTestReq2().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_backBtnActionPerformed

    //New Test Request Button
    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        new NewTestReq().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_addBtnActionPerformed

    //Home Button
    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        new ClinicianHome().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeBtnActionPerformed

    //Save Button
    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        
    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewTestRequest3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewTestRequest3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewTestRequest3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewTestRequest3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewTestRequest3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel bodyPanel;
    private javax.swing.JPanel btnPanel;
    private javax.swing.JLabel clinicianIDLbl1;
    private javax.swing.JTextField clinicianIDTxtFld;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JTextField dateTxtFld1;
    private javax.swing.JTextField examTxtFld;
    private javax.swing.JButton exitBtn;
    private javax.swing.JLabel exmaIDLbl;
    private javax.swing.JPanel headPanel;
    private javax.swing.JPanel headSubPanel1;
    private javax.swing.JPanel headSubPanel2;
    private javax.swing.JPanel headSubPanel3;
    private javax.swing.JButton homeBtn;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox labIDCmbBx;
    private javax.swing.JLabel labIDlbl1;
    private javax.swing.JLabel labIcon;
    private javax.swing.JLabel notesLbl;
    private javax.swing.JTextArea notesTxtArea;
    private javax.swing.JLabel patientIDLbl1;
    private javax.swing.JTextField patientIDTxtFld;
    private javax.swing.JButton saveBtn;
    private javax.swing.JPanel subBodyPanel;
    private javax.swing.JLabel subheadingLbl;
    private javax.swing.JLabel testReqLbl3;
    private javax.swing.JPanel testReqPanel3;
    private javax.swing.JComboBox testTypeCmbBx1;
    private javax.swing.JLabel testTypeLbl1;
    // End of variables declaration//GEN-END:variables
}
